// Thin wrappers over the two browser speech APIs.
//
// NOTE for later: SpeechRecognition on Chrome streams audio to Google's
// servers, which is the wrong privacy story for a child health app. It is fine
// for prototyping and demos. The production options are (a) record audio and
// send it to a transcription service we control, or (b) wrap this app in
// Capacitor and call Apple's on-device recognizer. Either swap happens behind
// `listen()` without touching any screen.

export const canSpeak = () =>
  typeof window !== 'undefined' && 'speechSynthesis' in window

// Pre-generated audio first, browser speech second.
//
// The browser's own voices are whatever the device happens to have installed,
// and on a Mac that is usually the ~1MB "compact" tier -- grainy to the point
// of being hard to follow -- sitting in a list alongside novelty voices called
// Zarvox and Bad News. Since the app never named a voice, the OS picked the
// default, and a child could be read their symptoms by a joke robot. Files
// generated by `scripts/build-audio.mjs` make every device sound identical.
//
// The filename is a hash of the text, so editing a question's wording yields a
// new name, the old clip is simply never requested, and nothing can play stale
// audio over changed words. A missing file is not an error -- it falls through
// to the browser voice, which is what happens for the three lines that
// interpolate a child's name or body part at runtime.

const AUDIO_BASE = '/audio'
let current = null

// Matches `hashOf` in scripts/build-audio.mjs. SubtleCrypto is async and only
// available over https/localhost, so this is a small synchronous SHA-1 rather
// than a dependency or an await in a hot path.
const sha1Hex = (str) => {
  const msg = new TextEncoder().encode(str)
  const len = msg.length
  const withPad = new Uint8Array((((len + 8) >> 6) + 1) * 64)
  withPad.set(msg)
  withPad[len] = 0x80
  new DataView(withPad.buffer).setUint32(withPad.length - 4, len * 8, false)

  let [h0, h1, h2, h3, h4] = [0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476, 0xc3d2e1f0]
  const w = new Uint32Array(80)
  const view = new DataView(withPad.buffer)
  for (let i = 0; i < withPad.length; i += 64) {
    for (let j = 0; j < 16; j += 1) w[j] = view.getUint32(i + j * 4, false)
    for (let j = 16; j < 80; j += 1) {
      const n = w[j - 3] ^ w[j - 8] ^ w[j - 14] ^ w[j - 16]
      w[j] = (n << 1) | (n >>> 31)
    }
    let [a, b, c, d, e] = [h0, h1, h2, h3, h4]
    for (let j = 0; j < 80; j += 1) {
      const [f, k] =
        j < 20 ? [(b & c) | (~b & d), 0x5a827999]
        : j < 40 ? [b ^ c ^ d, 0x6ed9eba1]
        : j < 60 ? [(b & c) | (b & d) | (c & d), 0x8f1bbcdc]
        : [b ^ c ^ d, 0xca62c1d6]
      const t = (((a << 5) | (a >>> 27)) + f + e + k + w[j]) >>> 0
      ;[e, d, c, b, a] = [d, c, (b << 30) | (b >>> 2), a, t]
    }
    ;[h0, h1, h2, h3, h4] = [(h0 + a) >>> 0, (h1 + b) >>> 0, (h2 + c) >>> 0, (h3 + d) >>> 0, (h4 + e) >>> 0]
  }
  return [h0, h1, h2, h3, h4].map((n) => n.toString(16).padStart(8, '0')).join('')
}

export const clipUrl = (text) => `${AUDIO_BASE}/${sha1Hex(text.trim()).slice(0, 16)}.mp3`

const speakWithBrowser = (text, voiceOpts = {}) => {
  if (!canSpeak()) return
  window.speechSynthesis.cancel()
  // Chrome silently pauses the engine after inactivity and never reports it.
  window.speechSynthesis.resume()
  const utter = new SpeechSynthesisUtterance(text)
  utter.pitch = voiceOpts.pitch ?? 1.2
  // Not below 1. Slowing a synthetic voice does not make it gentler, it makes
  // it ominous, and the old default of 0.9 was a large part of why this sounded
  // frightening rather than kind.
  utter.rate = voiceOpts.rate ?? 1
  utter.volume = 1
  window.speechSynthesis.speak(utter)
}

// `onEnd` fires when the clip finishes -- or immediately after the browser
// voice is handed the line, since a caller that waits for speech to end must
// not hang when there is no clip to wait for.
export const speak = (text, voiceOpts = {}, onEnd) => {
  if (!text) return
  stopSpeaking()
  const audio = new Audio(clipUrl(text))
  audio.volume = 1
  current = audio
  audio.onended = () => {
    if (current === audio) current = null
    onEnd?.()
  }

  // `play()` returns a promise, and THAT is the subtle part. Calling pause() on
  // an audio element whose play() has not yet resolved makes the promise reject
  // with AbortError -- so when a screen changes and the cleanup stops the clip,
  // the rejection looks exactly like "file missing" and the fallback fires. The
  // symptom is the good clip being cut off and the flat system voice reading the
  // PREVIOUS screen's line over the new one, which reads as the audio being out
  // of sync with the app.
  //
  // So a rejection only means "fall back" if this clip is still the current one.
  // If something else has taken over, the stop was deliberate and there is
  // nothing to recover from.
  audio.play().catch(() => {
    if (current !== audio) return
    current = null
    speakWithBrowser(text, voiceOpts)
    onEnd?.()
  })
}

export const stopSpeaking = () => {
  if (current) {
    const audio = current
    // Cleared BEFORE pausing, so the catch above can tell a deliberate stop
    // from a genuine failure.
    current = null
    audio.pause()
  }
  if (canSpeak()) window.speechSynthesis.cancel()
}

const Recognition =
  typeof window !== 'undefined'
    ? window.SpeechRecognition || window.webkitSpeechRecognition
    : null

export const canListen = () => Boolean(Recognition)

// Returns a handle with .stop(). Calls onResult with the running transcript
// (interim + final) so the child sees words appear as they talk.
export const listen = ({ onResult, onEnd, onError }) => {
  if (!Recognition) {
    onError?.('unsupported')
    return { stop: () => {} }
  }

  const rec = new Recognition()
  rec.lang = 'en-US'
  rec.continuous = true
  rec.interimResults = true

  let finalText = ''

  rec.onresult = (event) => {
    let interim = ''
    for (let i = event.resultIndex; i < event.results.length; i += 1) {
      const chunk = event.results[i][0].transcript
      if (event.results[i].isFinal) finalText += chunk
      else interim += chunk
    }
    onResult?.((finalText + interim).trim(), finalText.trim())
  }

  rec.onerror = (event) => onError?.(event.error)
  rec.onend = () => onEnd?.(finalText.trim())

  try {
    rec.start()
  } catch {
    onError?.('start-failed')
  }

  return {
    stop: () => {
      try {
        rec.stop()
      } catch {
        /* already stopped */
      }
    },
  }
}
