// Thin wrappers over the two browser speech APIs.
//
// NOTE for later: SpeechRecognition on Chrome streams audio to Google's
// servers, which is the wrong privacy story for a child health app. It is fine
// for prototyping and demos. The production options are (a) record audio and
// send it to a transcription service we control, or (b) wrap this app in
// Capacitor and call Apple's on-device recognizer. Either swap happens behind
// `listen()` without touching any screen.

// The app's spoken audio is pre-generated, and only pre-generated.
//
// The browser's own voices are whatever the device happens to have installed,
// and on a Mac that is usually the ~1MB "compact" tier -- grainy to the point
// of being hard to follow -- sitting in a list alongside novelty voices called
// Zarvox and Bad News. Since the app never named a voice, the OS picked the
// default, and a child could be read their symptoms by a joke robot. Files
// generated by `scripts/build-audio.mjs` make every device sound identical.
//
// The filename is a hash of the text, so editing a question's wording yields a
// new name, the old clip is simply never requested, and nothing can play stale
// audio over changed words. A missing file is not an error either -- the line
// is shown and not spoken. That is why a line assembled at runtime, around a
// child's name or the part they tapped, can never be heard: its text is not
// known when the clips are made, so it has no clip and never will.

const AUDIO_BASE = '/audio'
let current = null

// Matches `hashOf` in scripts/build-audio.mjs. SubtleCrypto is async and only
// available over https/localhost, so this is a small synchronous SHA-1 rather
// than a dependency or an await in a hot path.
const sha1Hex = (str) => {
  const msg = new TextEncoder().encode(str)
  const len = msg.length
  const withPad = new Uint8Array((((len + 8) >> 6) + 1) * 64)
  withPad.set(msg)
  withPad[len] = 0x80
  new DataView(withPad.buffer).setUint32(withPad.length - 4, len * 8, false)

  let [h0, h1, h2, h3, h4] = [0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476, 0xc3d2e1f0]
  const w = new Uint32Array(80)
  const view = new DataView(withPad.buffer)
  for (let i = 0; i < withPad.length; i += 64) {
    for (let j = 0; j < 16; j += 1) w[j] = view.getUint32(i + j * 4, false)
    for (let j = 16; j < 80; j += 1) {
      const n = w[j - 3] ^ w[j - 8] ^ w[j - 14] ^ w[j - 16]
      w[j] = (n << 1) | (n >>> 31)
    }
    let [a, b, c, d, e] = [h0, h1, h2, h3, h4]
    for (let j = 0; j < 80; j += 1) {
      const [f, k] =
        j < 20 ? [(b & c) | (~b & d), 0x5a827999]
        : j < 40 ? [b ^ c ^ d, 0x6ed9eba1]
        : j < 60 ? [(b & c) | (b & d) | (c & d), 0x8f1bbcdc]
        : [b ^ c ^ d, 0xca62c1d6]
      const t = (((a << 5) | (a >>> 27)) + f + e + k + w[j]) >>> 0
      ;[e, d, c, b, a] = [d, c, (b << 30) | (b >>> 2), a, t]
    }
    ;[h0, h1, h2, h3, h4] = [(h0 + a) >>> 0, (h1 + b) >>> 0, (h2 + c) >>> 0, (h3 + d) >>> 0, (h4 + e) >>> 0]
  }
  return [h0, h1, h2, h3, h4].map((n) => n.toString(16).padStart(8, '0')).join('')
}

export const clipUrl = (text) => `${AUDIO_BASE}/${sha1Hex(text.trim()).slice(0, 16)}.mp3`

// THE GUIDE HAS ONE VOICE, OR NONE.
//
// There used to be a fallback here: a line with no clip was read by
// `speechSynthesis`, on the reasoning that a plain voice beats silence. Tested
// on a real device, it is the other way round. The browser's voice is a
// different speaker mid-conversation -- flatter, differently paced, and on a
// Mac often the ~1MB compact tier -- so the child hears the app change
// character for one sentence. Every line that fell through was one a child met
// early: the home greeting, the setup sample, the gate question. All three were
// reported as sounding wrong before the cause was understood, and none of them
// read as "missing audio". They read as the app being slightly off.
//
// So an un-recorded line is now simply not spoken. The words are on screen
// either way -- that is a rule of the whole flow, not a concession here -- and
// silence is honest in a way a second voice is not.
//
// The practical consequence: adding a line to a screen adds a silent line until
// someone runs the generator. `node scripts/build-audio.mjs --live --dry` lists
// exactly what is missing, and the check costs nothing.

// `onEnd` fires when the line is over: the clip's `ended` event, or at once
// when there is no clip to play. Callers use it both to advance (IntroScreen)
// and to stop the guide's mouth moving, so it must mean "the sentence is over",
// never "the sentence has started" -- and it must fire even when nothing is
// spoken, or a caller waiting on it hangs and a screen never advances.
//
// `voiceOpts` is kept on the signature and unused. It carried pitch and rate
// for the synthetic voice; a recorded clip has its own. It stays because the
// characters each declare one (see data/characters.js) and a second guide would
// be a second set of clips chosen here.
export const speak = (text, voiceOpts = {}, onEnd) => {
  if (!text) {
    onEnd?.()
    return
  }
  stopSpeaking()
  const audio = new Audio(clipUrl(text))
  audio.volume = 1
  current = audio
  audio.onended = () => {
    if (current === audio) current = null
    onEnd?.()
  }

  // A rejection here is either a missing clip or a deliberate stop -- calling
  // pause() on an element whose play() has not resolved rejects with
  // AbortError, which is indistinguishable from "file not found". Both end the
  // same way now that nothing speaks in the guide's place, but `onEnd` must
  // only fire for THIS clip: if something else has taken over, that clip owns
  // the mouth and the callback, and stopping a line the child has already left
  // behind must not reach back to end the line they are on.
  audio.play().catch(() => {
    if (current !== audio) return
    current = null
    onEnd?.()
  })
}

export const stopSpeaking = () => {
  if (current) {
    const audio = current
    // Cleared BEFORE pausing, so the catch above can tell a deliberate stop
    // from a genuine failure.
    current = null
    audio.pause()
  }
  // Nothing cancels `speechSynthesis` here any more: this app never hands it a
  // line. See the note above `speak`.
}

const Recognition =
  typeof window !== 'undefined'
    ? window.SpeechRecognition || window.webkitSpeechRecognition
    : null

export const canListen = () => Boolean(Recognition)

// Returns a handle with .stop(). Calls onResult with the running transcript
// (interim + final) so the child sees words appear as they talk.
export const listen = ({ onResult, onEnd, onError }) => {
  if (!Recognition) {
    onError?.('unsupported')
    return { stop: () => {} }
  }

  const rec = new Recognition()
  rec.lang = 'en-US'
  rec.continuous = true
  rec.interimResults = true

  let finalText = ''

  rec.onresult = (event) => {
    let interim = ''
    for (let i = event.resultIndex; i < event.results.length; i += 1) {
      const chunk = event.results[i][0].transcript
      if (event.results[i].isFinal) finalText += chunk
      else interim += chunk
    }
    onResult?.((finalText + interim).trim(), finalText.trim())
  }

  rec.onerror = (event) => onError?.(event.error)
  rec.onend = () => onEnd?.(finalText.trim())

  try {
    rec.start()
  } catch {
    onError?.('start-failed')
  }

  return {
    stop: () => {
      try {
        rec.stop()
      } catch {
        /* already stopped */
      }
    },
  }
}
