// Generate packets/EVIDENCE.md -- the consolidated evidence base.
//
//   node scripts/evidence-report.mjs
//
// This is the document to put in front of someone who asks what the app's
// questions are based on. It is deliberately not a summary of the packets: it
// is the bibliography, plus an honest count of what was read versus cited.

import { readFileSync, writeFileSync } from 'node:fs'
import { packetDirs } from './packet-paths.mjs'

const rows = []
const sections = []

for (const dir of packetDirs()) {
  const meta = JSON.parse(readFileSync(`${dir}/meta.json`, 'utf8'))
  const md = readFileSync(`${dir}/packet.md`, 'utf8')
  // Tolerates a qualifier and a line wrap between "first-hand" and the count.
  // chest/pain's line reads "first-hand *in this reconstruction*: 6 of 7" because
  // its prose was rebuilt after the original run was killed, and that disclosure
  // is worth more than a regex-friendly status line.
  const status = (md.match(/sources verified first-hand[^:]{0,60}:\s*\**\s*(\d+)\s*of\s*(\d+)/i) || [])
  const items = [...md.matchAll(/^\|\s*(\d+)\s*\|([^|]*)\|([^|]*)\|([^|]*)\|/gm)]
  const yes = items.filter(([, , , , v]) => /^\s*\*{0,2}yes/i.test(v)).length
  const partial = items.filter(([, , , , v]) => /^\s*\*{0,2}partial/i.test(v)).length

  rows.push({ id: meta.id, group: meta.group, area: dir.split('/')[1],
              read: status[1] ?? '?', cited: status[2] ?? '?',
              items: items.length, yes, partial })

  // The Sources section verbatim -- no paraphrase, because paraphrasing a
  // bibliography is how "cited, not read" quietly becomes "cited".
  const src = (md.match(/^## Sources\n([\s\S]*?)(?=\n## )/m) || ['', '(none listed)'])[1].trim()
  sections.push(`### ${meta.id}  ·  body area \`${meta.group}\`\n\n` +
                `Sources read first-hand: **${status[1] ?? '?'} of ${status[2] ?? '?'}**\n\n${src}\n`)
}

const tot = rows.reduce((a, r) => ({
  read: a.read + (+r.read || 0), cited: a.cited + (+r.cited || 0),
  items: a.items + r.items, yes: a.yes + r.yes, partial: a.partial + r.partial,
}), { read: 0, cited: 0, items: 0, yes: 0, partial: 0 })

writeFileSync('packets/EVIDENCE.md', `# Evidence base

Generated by \`scripts/evidence-report.mjs\` — do not hand-edit.

> **Before citing this anywhere, read \`packets/LIMITATIONS.md\`.** Nothing here
> has been clinically reviewed. "Read first-hand" means the pipeline fetched and
> quoted the source directly; it does not mean a clinician checked the
> selection, interpretation, or omission of criteria.

## Summary

**${tot.cited} sources consulted across ${rows.length} presenting complaints, ${tot.read} read first-hand.**
From those, **${tot.items} assessment criteria** were extracted, of which
**${tot.yes} were judged child-reportable** and **${tot.partial} partially so** —
the remainder being examination findings, observer judgements, or laboratory
results that a child cannot report about themselves and which never become
questions.

| Body area | Complaint | Sources read / cited | Criteria | Child-reportable |
|---|---|---|---|---|
${rows.map((r) => `| \`${r.area}\` | ${r.id} | ${r.read} / ${r.cited} | ${r.items} | ${r.yes} yes, ${r.partial} partial |`).join('\n')}
| | **total** | **${tot.read} / ${tot.cited}** | **${tot.items}** | **${tot.yes} yes, ${tot.partial} partial** |

## How a criterion becomes a question

1. A source is fetched and its criteria extracted **verbatim** — never paraphrased.
2. Each criterion is judged: can a child aged 4–12 report this about themselves?
   Examination findings and observer judgements are excluded and the exclusion
   is recorded with its reasoning.
3. Surviving criteria are worded for two age tiers under per-packet rules
   covering register, leading questions, and severity language.
4. Every candidate question must cite the numbered criterion it descends from.
   \`scripts/build-bank.mjs\` **refuses to ship a question that does not**, and an
   item with no recorded citation ships \`cite: null\` with a warning rather than
   borrowing another packet's.
5. A human accepts or rejects each candidate, with the reason recorded.
   Rejections are kept as the record that the set was evaluated.

## Full bibliography by complaint

${sections.join('\n')}
`)
console.log(`packets/EVIDENCE.md — ${tot.cited} sources, ${tot.read} read first-hand, ${tot.items} criteria`)
