// Generate packets/QUESTIONS.md -- every shipping question with the evidence
// behind it, grouped by packet.
//
//   node scripts/questions-report.mjs
//
// EVIDENCE.md is the bibliography: which sources were consulted per packet.
// This is the other direction -- start from a question a child is actually
// asked and find what it rests on. It is the document to open when someone
// points at one question and says "why do you ask that?".
//
// Regenerate after any review, ranking change, or rebuild. A stale copy that
// contradicts the metas is worse than no copy.

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { packetDirs } from './packet-paths.mjs'

const CAP = 6 // most questions any one packet can reach in a single report

const owners = new Map()
for (const dir of packetDirs()) {
  if (!existsSync(`${dir}/candidates.json`)) continue
  const j = JSON.parse(readFileSync(`${dir}/candidates.json`, 'utf8'))
  for (const c of j.candidates)
    if (c.review?.status === 'accepted' && c.fact) {
      if (!owners.has(c.fact)) owners.set(c.fact, new Set())
      owners.get(c.fact).add(j.packet.id)
    }
}

const out = []
let totalShipping = 0, totalBelow = 0, packets = 0

for (const dir of packetDirs()) {
  if (!existsSync(`${dir}/candidates.json`)) continue
  const meta = JSON.parse(readFileSync(`${dir}/meta.json`, 'utf8'))
  const j = JSON.parse(readFileSync(`${dir}/candidates.json`, 'utf8'))
  const md = existsSync(`${dir}/packet.md`) ? readFileSync(`${dir}/packet.md`, 'utf8') : ''
  const status = (md.match(/sources verified first-hand[^:]{0,60}:\s*\**\s*(\d+)\s*of\s*(\d+)/i) || [])

  const accepted = j.candidates.filter((c) => c.review?.status === 'accepted')
  const byItem = new Map()
  for (const c of accepted) {
    if (!byItem.has(c.traces_to)) byItem.set(c.traces_to, [])
    byItem.get(c.traces_to).push(c)
  }
  const ranked = meta.itemRank.filter((i) => byItem.has(i))
  if (!ranked.length) continue
  packets += 1

  out.push('---', '', `## ${meta.id}`, '')
  const bits = [`body area \`${meta.group}\``]
  if (meta.depth) bits.push(`depth \`${meta.depth}\``)
  if (meta.mechanism) bits.push(`mechanism \`${meta.mechanism}\``)
  bits.push(`packetRank ${meta.packetRank ?? 50}`)
  out.push(bits.join(' · '), '')
  if (status[1]) out.push(`Sources verified first-hand: **${status[1]} of ${status[2]}**`, '')
  out.push(`${accepted.length} accepted questions across ${ranked.length} items. ` +
           `A child reaches at most the first ${Math.min(CAP, ranked.length)}.`, '')

  ranked.forEach((item, idx) => {
    const cands = byItem.get(item)
    const lead = cands[0]
    const ships = idx < CAP
    if (ships) totalShipping += 1; else totalBelow += 1
    const shared = lead.fact && (owners.get(lead.fact)?.size ?? 0) > 1
    out.push(`### ${ships ? `${idx + 1}.` : '—'} ${lead.q.older}`, '')
    out.push(`- **Younger (4–7):** ${lead.q.young}`)
    out.push(`- **Answer:** \`${lead.answers ?? 'yesno'}\`` +
      (lead.options ? ` — ${lead.options.map((o) => typeof o.label === 'string' ? o.label : o.label.older).join(' / ')}` : ''))
    out.push(`- **Establishes:** \`${lead.fact ?? '(untagged — this question is never deduplicated against another packet)'}\`` +
      (shared ? ` — also asked by ${[...owners.get(lead.fact)].filter((p) => p !== meta.id).join(', ')}, so only one of them is ever asked` : ''))
    out.push(`- **Packet item ${item}**, rank ${idx + 1} of ${ranked.length}` +
      (ships ? '' : ' — **below the cut**, kept and cited but not currently reached by any child'))
    if (meta.minAge?.[String(item)]) out.push(`- **Only asked from age ${meta.minAge[String(item)]}**`)
    const dur = meta.durations.exceptions?.[String(item)] ?? meta.durations.default
    out.push(`- **Asked when the problem started:** ${dur.join(', ')}`)
    out.push('', '**Evidence:**', '')
    const cite = meta.cite?.[String(item)]
    out.push(cite ? `> ${String(cite).replace(/\n+/g, ' ')}` : '> *(no citation recorded — this is a defect, not a question without evidence)*')
    if (cands.length > 1) {
      out.push('', `<details><summary>${cands.length - 1} other accepted wording${cands.length > 2 ? 's' : ''} for this item (not currently used)</summary>`, '')
      for (const alt of cands.slice(1)) out.push(`- ${alt.q.older}  ·  younger: ${alt.q.young}`)
      out.push('', '</details>')
    }
    out.push('')
  })
}

const head = []
head.push('# Every question, and what it rests on', '')
head.push('Generated by `scripts/questions-report.mjs` — do not hand-edit.', '')
head.push('> **Before citing this anywhere, read `packets/LIMITATIONS.md`.** Nothing here')
head.push('> has been clinically reviewed. The citations show what a question was derived')
head.push('> from; they do not mean a clinician checked the derivation, the wording, or')
head.push('> what was left out.', '')
head.push('`EVIDENCE.md` is the bibliography — which sources each packet consulted. This')
head.push('is the other direction: start from a question a child is actually asked and')
head.push('find what it rests on.', '')
head.push('## How to read this', '')
head.push(`**${totalShipping} questions currently reach children; ${totalBelow} sit below the cut.**`)
head.push(`Across ${packets} packets.`, '')
head.push('A child answers **5 questions under age 8 and 6 from age 8 up**, spent')
head.push('round-robin across every body area they tapped, plus a reserved "has this')
head.push('happened to you before". So only the top of each packet is ever reached.')
head.push('Numbered entries ship; entries marked — are kept, cited and ranked but not')
head.push('currently asked. They become reachable if the cap grows, or when a duration')
head.push('or age filter removes something above them.', '')
head.push('**Establishes** is the fact a question pins down. Facts are shared across')
head.push('packets deliberately, and only one question per fact is ever asked — so a')
head.push('child who taps two body areas is not asked the same thing twice.', '')

writeFileSync('packets/QUESTIONS.md', head.concat(out).join('\n') + '\n')
console.log(`packets/QUESTIONS.md — ${totalShipping} shipping, ${totalBelow} below the cut, ${packets} packets`)
